#!/usr/bin/env python2
## -*- mode: python; coding: utf-8 -*-
##
## netperf-wrapper.py
##
## Author:   Toke Høiland-Jørgensen (toke@toke.dk)
## Date:     October 8th, 2012
## Copyright (c) 2012, Toke Høiland-Jørgensen
##
## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program.  If not, see <http://www.gnu.org/licenses/>.

import sys

try:
    import optparse, os

    from netperf_wrapper import aggregators, formatters
    from netperf_wrapper.settings import load

    if __name__ == "__main__":
        try:
            settings,results = load()

            agg = aggregators.new(settings)
            formatter = formatters.new(settings)

            if not results[0]:
                results[0] = agg.postprocess(agg.aggregate(results[0]))
                results[0].dump_dir(os.path.dirname(settings.OUTPUT) or ".")
            formatter.format(results)

        except RuntimeError as e:
            sys.stderr.write("Error occurred: %s\n"% str(e))
            sys.exit(1)
except KeyboardInterrupt:
    try:
        agg.kill_runners()
    except NameError:
        pass
    sys.exit(1)
